---
title: "Case_Study"
author: "Yiqian"
date: "2025-06-27"
output: html_document
---
# CVD

## Source

```{r}
load("cardiovascular_wgs.RData")
#library(devtools)
#devtools::install_github("YiqianZhang1004/BetaTREND")
library(BetaTREND)
library(phyloseq)
library(vegan)
```

## Age
### Bray
```{r}
age <- as.numeric(sample_data(ps)[["Age..years."]])
keep <- !is.na(age)   
ps_filt <- prune_samples(keep, ps)  
age_filt <- as.numeric(sample_data(ps_filt)[["Age..years."]] )
dist_bray_filt <- phyloseq::distance(ps_filt, method = "bray")
res <- BetaTREND::gradient_projection(dist_bray_filt, age_filt)
res
evaluate_consistency_metrics(pcoa_mat = res$PCoA_coordinates,projection_scores = res$projection_scores,)
cjtt_u_test(dist_bray_filt, age_filt, var_method = "analytic")
# cjtt_u_test(dist_bray_filt, age_filt, var_method = "jackknife") Take too long
# cjtt_u_test(dist_bray_filt, age_filt, var_method = "bootstrap")
# cjtt_u_test(dist_bray_filt, age_filt, permutation = T)
gco_decomposition(pcoa_mat = res$PCoA_coordinates,projection_scores = res$projection_scores)
```


### Unweighted UniFrac
```{r}
dist_bray_filt <- phyloseq::distance(ps_filt, method = "uunifrac")
res <- BetaTREND::gradient_projection(dist_bray_filt, age_filt)
res
evaluate_consistency_metrics(pcoa_mat = res$PCoA_coordinates,projection_scores = res$projection_scores,)
cjtt_u_test(dist_bray_filt, age_filt, var_method = "analytic")
# cjtt_u_test(dist_bray_filt, age_filt, var_method = "jackknife") Take too long
# cjtt_u_test(dist_bray_filt, age_filt, var_method = "bootstrap")
# cjtt_u_test(dist_bray_filt, age_filt, permutation = T)
gco_decomposition(pcoa_mat = res$PCoA_coordinates,projection_scores = res$projection_scores)
```

### weighted UniFrac
```{r}
dist_bray_filt <- phyloseq::distance(ps_filt, method = "wunifrac")
res <- BetaTREND::gradient_projection(dist_bray_filt, age_filt)
res
evaluate_consistency_metrics(pcoa_mat = res$PCoA_coordinates,projection_scores = res$projection_scores,)
cjtt_u_test(dist_bray_filt, age_filt, var_method = "analytic")
# cjtt_u_test(dist_bray_filt, age_filt, var_method = "jackknife") Take too long
# cjtt_u_test(dist_bray_filt, age_filt, var_method = "bootstrap")
# cjtt_u_test(dist_bray_filt, age_filt, permutation = T)
gco_decomposition(pcoa_mat = res$PCoA_coordinates,projection_scores = res$projection_scores)
```

## BMI

```{r}
BMI <- as.numeric(sample_data(ps)[["BMI..kg.m.."]])
keep <- !is.na(BMI)   
ps_filt <- prune_samples(keep, ps)  
BMI_filt <- as.numeric(sample_data(ps_filt)[["BMI..kg.m.."]])
dist_bray_filt <- phyloseq::distance(ps_filt, method = "bray")
res <- BetaTREND::gradient_projection(dist_bray_filt, BMI_filt)
res
evaluate_consistency_metrics(pcoa_mat = res$PCoA_coordinates,projection_scores = res$projection_scores)
cjtt_u_test(dist_bray_filt, BMI_filt, var_method = "analytic")
gco_decomposition(pcoa_mat = res$PCoA_coordinates,projection_scores = res$projection_scores)
```

## HbA1c

```{r}
HbA1c <- as.numeric(sample_data(ps)[["HbA1c...."]])
keep <- !is.na(HbA1c)   
ps_filt <- prune_samples(keep, ps)  
HbA1c_filt <- as.numeric(sample_data(ps_filt)[["HbA1c...."]])
dist_bray_filt <- phyloseq::distance(ps_filt, method = "bray")
res <- BetaTREND::gradient_projection(dist_bray_filt, HbA1c_filt)
res
evaluate_consistency_metrics(pcoa_mat = res$PCoA_coordinates,projection_scores = res$projection_scores)
cjtt_u_test(dist_bray_filt, HbA1c_filt, var_method = "analytic")
gco_decomposition(pcoa_mat = res$PCoA_coordinates,projection_scores = res$projection_scores)
```

## CRP

```{r}
CRP <- as.numeric(sample_data(ps)[["Fasting.plasma.CRP..mg.L."]])
keep <- !is.na(CRP)   
ps_filt <- prune_samples(keep, ps)  
CRP_filt <- as.numeric(sample_data(ps_filt)[["Fasting.plasma.CRP..mg.L."]])
dist_bray_filt <- phyloseq::distance(ps_filt, method = "bray")
res <- BetaTREND::gradient_projection(dist_bray_filt, CRP_filt)
res
evaluate_consistency_metrics(pcoa_mat = res$PCoA_coordinates,projection_scores = res$projection_scores)
cjtt_u_test(dist_bray_filt, CRP_filt, var_method = "analytic")
gco_decomposition(pcoa_mat = res$PCoA_coordinates,projection_scores = res$projection_scores)
```

# IBD

## Source

```{r}
load("GUT(1629).RData")
```

## timepoint

```{r}
timepoint <- as.numeric(sample_data(ps1)[["timepoint"]])
keep <- !is.na(timepoint)   
ps_filt <- prune_samples(keep, ps1)  
timepoint_filt <- as.numeric(sample_data(ps_filt)[["timepoint"]])
dist_bray_filt <- phyloseq::distance(ps_filt, method = "bray")
res <- BetaTREND::gradient_projection(dist_bray_filt, timepoint_filt)
res
evaluate_consistency_metrics(pcoa_mat = res$PCoA_coordinates,projection_scores = res$projection_scores)
cjtt_u_test(dist_bray_filt, timepoint_filt, var_method = "analytic")
gco_decomposition(pcoa_mat = res$PCoA_coordinates,projection_scores = res$projection_scores)
```

## calprotectin

```{r}
calprotectin <- as.numeric(sample_data(ps1)[["calprotectin"]])
keep <- !is.na(calprotectin)   
ps_filt <- prune_samples(keep, ps1)  
calprotectin_filt <- as.numeric(sample_data(ps_filt)[["calprotectin"]])
dist_bray_filt <- phyloseq::distance(ps_filt, method = "bray")
res <- BetaTREND::gradient_projection(dist_bray_filt, calprotectin_filt)
res
evaluate_consistency_metrics(pcoa_mat = res$PCoA_coordinates,projection_scores = res$projection_scores)
cjtt_u_test(dist_bray_filt, calprotectin_filt, var_method = "analytic")
gco_decomposition(pcoa_mat = res$PCoA_coordinates,projection_scores = res$projection_scores)
```

## BMI

```{r}
bmi <- as.numeric(sample_data(ps1)[["bmi"]])
keep <- !is.na(bmi)   
ps_filt <- prune_samples(keep, ps1)  
bmi_filt <- as.numeric(sample_data(ps_filt)[["bmi"]])
dist_bray_filt <- phyloseq::distance(ps_filt, method = "bray")
res <- BetaTREND::gradient_projection(dist_bray_filt, bmi_filt)
res
evaluate_consistency_metrics(pcoa_mat = res$PCoA_coordinates,projection_scores = res$projection_scores)
cjtt_u_test(dist_bray_filt, bmi_filt, var_method = "analytic")
gco_decomposition(pcoa_mat = res$PCoA_coordinates,projection_scores = res$projection_scores)
```

## year_diagnosed

```{r}
year_diagnosed <- as.numeric(sample_data(ps1)[["year_diagnosed"]])
keep <- !is.na(year_diagnosed)   
ps_filt <- prune_samples(keep, ps1)  
year_diagnosed_filt <- as.numeric(sample_data(ps_filt)[["year_diagnosed"]])
dist_bray_filt <- phyloseq::distance(ps_filt, method = "bray")
res <- BetaTREND::gradient_projection(dist_bray_filt, year_diagnosed_filt)
res
evaluate_consistency_metrics(pcoa_mat = res$PCoA_coordinates,projection_scores = res$projection_scores)
cjtt_u_test(dist_bray_filt, year_diagnosed_filt, var_method = "analytic")
gco_decomposition(pcoa_mat = res$PCoA_coordinates,projection_scores = res$projection_scores)
```

# Ocean

## Source
```{r}
load("Ocean.RData")
```

## Depth nominal

```{r}
Depth.nominal <- as.numeric(sample_data(ps)[["Depth.nominal"]])
keep <- !is.na(Depth.nominal)   
ps_filt <- prune_samples(keep, ps)  
Depth.nominal_filt <- as.numeric(sample_data(ps_filt)[["Depth.nominal"]])
dist_bray_filt <- phyloseq::distance(ps_filt, method = "bray")
res <- BetaTREND::gradient_projection(dist_bray_filt, Depth.nominal_filt)
res
evaluate_consistency_metrics(pcoa_mat = res$PCoA_coordinates,projection_scores = res$projection_scores)
cjtt_u_test(dist_bray_filt, Depth.nominal_filt, var_method = "analytic")
gco_decomposition(pcoa_mat = res$PCoA_coordinates,projection_scores = res$projection_scores)
```

## Longitude

```{r}
Longitude <- as.numeric(sample_data(ps)[["Longitude"]])
keep <- !is.na(Longitude)   
ps_filt <- prune_samples(keep, ps)  
Longitude_filt <- as.numeric(sample_data(ps_filt)[["Longitude"]])
dist_bray_filt <- phyloseq::distance(ps_filt, method = "bray")
res <- BetaTREND::gradient_projection(dist_bray_filt, Longitude_filt)
res
evaluate_consistency_metrics(pcoa_mat = res$PCoA_coordinates,projection_scores = res$projection_scores)
cjtt_u_test(dist_bray_filt, Longitude_filt, var_method = "analytic")
gco_decomposition(pcoa_mat = res$PCoA_coordinates,projection_scores = res$projection_scores)
```

## Latitude

```{r}
Latitude <- as.numeric(sample_data(ps)[["Latitude"]])
keep <- !is.na(Latitude)   
ps_filt <- prune_samples(keep, ps)  
Latitude_filt <- as.numeric(sample_data(ps_filt)[["Latitude"]])
dist_bray_filt <- phyloseq::distance(ps_filt, method = "bray")
res <- BetaTREND::gradient_projection(dist_bray_filt, Latitude_filt)
res
evaluate_consistency_metrics(pcoa_mat = res$PCoA_coordinates,projection_scores = res$projection_scores)
cjtt_u_test(dist_bray_filt, Latitude_filt, var_method = "analytic")
gco_decomposition(pcoa_mat = res$PCoA_coordinates,projection_scores = res$projection_scores)
```

## Density

```{r}
Density <- as.numeric(sample_data(ps)[["Density"]])
keep <- !is.na(Density)   
ps_filt <- prune_samples(keep, ps)  
Density_filt <- as.numeric(sample_data(ps_filt)[["Density"]])
dist_bray_filt <- phyloseq::distance(ps_filt, method = "bray")
res <- BetaTREND::gradient_projection(dist_bray_filt, Density_filt)
res
evaluate_consistency_metrics(pcoa_mat = res$PCoA_coordinates,projection_scores = res$projection_scores)
cjtt_u_test(dist_bray_filt, Density_filt, var_method = "analytic")
gco_decomposition(pcoa_mat = res$PCoA_coordinates,projection_scores = res$projection_scores)
```


